version: '3.3'

services:
  api:
    image: mosmetall:production
    restart: on-failure
    command: sh scripts/start_api.sh
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DJANGO_PORT=${DJANGO_PORT}
    volumes:
      - ../scripts:/code/scripts
      - ../src:/code/src
    ports:
      - "${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}"
