version: '3.3'

services:
  api:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: mosmetall_api
    ports:
      - "${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}"
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DJANGO_PORT=${DJANGO_PORT}
    volumes:
      - ../scripts:/code/scripts
      - ../src:/code/src
